sudo: required
services:
  - docker

before_install:
  - docker build -t anuwatavis099/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anuwatavis099/docker-react npm run test -- --coverage
